/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.goobar.remote.config.promotion.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
// database [OPTIONS] COMMAND [ARGS]...



class Database: CliktCommand() {
    override fun run() = Unit
}

class Init: CliktCommand(help="Initialize the database") {
    override fun run() {
        echo("Initialized the database.")
    }
}

class Drop: CliktCommand(help="Drop the database") {
    override fun run() {
        echo("Dropped the database.")
    }
}

fun main(args: Array<String>) = Database()
    .subcommands(Init(), Drop())
    .main(args)
